# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07e321403b12e662a8cf2e4318786cd83688b6311d52e92f83e5a1f841c98a07fe2f63082aaf4ba9aaacb181ba35ce411e8f97d09770eecb8ee8d0fa096e82f6

test:
  secret_key_base: e125efd0a9d0040862e3244123c2dba6af59e429b5ff1d5ca8e366667c936ef232a51736c0315efa143e780a69ef89447239304eabcac4f37f551b67c2ca0c0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
